In [1]:
import numpy as np
import pandas as pd

# **SLR (sklearn)**

In [2]:
df=pd.read_csv('Salary_dataset.csv')

In [3]:
df.shape

(30, 2)

In [4]:
df.head()

YearsExperience  Salary
0              1.2   39344
1              1.4   46206
2              1.6   37732
3              2.1   43526
4              2.3   39892

In [5]:
# input and output
X = df.iloc[:,0:1]
Y = df.iloc[:,-1]

In [6]:
X

YearsExperience
0               1.2
1               1.4
2               1.6
3               2.1
4               2.3
5               3.0
6               3.1
7               3.3
8               3.3
9               3.8
10              4.0
11              4.1
12              4.1
13              4.2
14              4.6
15              5.0
16              5.2
17              5.4
18              6.0
19              6.1
20              6.9
21              7.2
22              8.0
23              8.3
24              8.8
25              9.1
26              9.6
27              9.7
28             10.4
29             10.6

In [7]:
# train test split
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

In [8]:
X_test

YearsExperience
1               1.4
0               1.2
14              4.6
9               3.8
21              7.2
19              6.1

In [9]:
# Using Sklearn's SLR
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

lr.fit(X_train,Y_train)

LinearRegression()

In [10]:
X_test

YearsExperience
1               1.4
0               1.2
14              4.6
9               3.8
21              7.2
19              6.1

In [11]:
Y_test

1     46206
0     39344
14    61112
9     57190
21    98274
19    93941
Name: Salary, dtype: int64

In [12]:
# prediction
lr.predict(X_test.iloc[3].values.reshape(1,1))

C:\Python310\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([59801.64062805])

In [13]:
lr.coef_

array([9569.58688543])

In [14]:
lr.intercept_

23437.210463405063

In [15]:
lr.predict(X_test.iloc[0].values.reshape(1,1))

C:\Python310\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([36834.63210301])

# **SLR (mine)**

In [16]:
# Creating my own SLR Class
class MySLR:
    
    def __init__(self):
        self.m = None
        self.b = None
        
    def fit(self,X_train,y_train):
        
        num = 0
        den = 0
        
        for i in range(X_train.shape[0]):
            
            num = num + ((X_train[i] - X_train.mean())*(y_train[i] - y_train.mean()))
            den = den + ((X_train[i] - X_train.mean())*(X_train[i] - X_train.mean()))
        
        self.m = num/den
        self.b = y_train.mean() - (self.m * X_train.mean())
        print(self.m)
        print(self.b)       
    
    def predict(self,X_test):
        print(X_test)
        
        return self.m * X_test + self.b

In [17]:
lr1=MySLR()

In [18]:
X1=df.iloc[:,0].values
Y1=df.iloc[:,1].values

In [19]:
X1

array([ 1.2,  1.4,  1.6,  2.1,  2.3,  3. ,  3.1,  3.3,  3.3,  3.8,  4. ,
        4.1,  4.1,  4.2,  4.6,  5. ,  5.2,  5.4,  6. ,  6.1,  6.9,  7.2,
        8. ,  8.3,  8.8,  9.1,  9.6,  9.7, 10.4, 10.6])

In [20]:
# train test split
from sklearn.model_selection import train_test_split
X_train1,X_test1,Y_train1,Y_test1=train_test_split(X1,Y1,test_size=0.2,random_state=2)

In [21]:
lr1.fit(X_train1,Y_train1)

9569.586885432866
23437.21046340505


In [22]:
X_train1[0]

8.3

In [23]:
X_test1

array([1.4, 1.2, 4.6, 3.8, 7.2, 6.1])

In [24]:
lr1.predict(X_test1[0])

1.4


36834.632103011056

# **MLR (mine)**

In [25]:
# Creating my own MLR Class
class MyMLR:
    
    def __init__(self):
        self.m = None
        self.b = None
        
    def fit(self,X_train,y_train):
        X_train=np.insert(X_train,0,1,axis=1) # inserting all 1 at 0th column
        
        # calculating coeffs
        betas=np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.b=betas[0]
        self.m=betas[1:]
    
    def predict(self,X_test):
        y_pred=np.dot(X_test,self.m)+self.b
        return y_pred

In [26]:
df1=pd.read_csv('Fish.csv')

In [27]:
df1.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [28]:
X2=df1.iloc[:,1:6].values
Y2=df1.iloc[:,6].values

In [29]:
Y2

array([4.02  , 4.3056, 4.6961, 4.4555, 5.134 , 4.9274, 5.2785, 4.69  ,
       4.8438, 4.9594, 5.1042, 4.8146, 4.368 , 5.0728, 5.1708, 5.58  ,
       5.2854, 5.1975, 5.1338, 5.7276, 5.5695, 5.3704, 5.2801, 6.1306,
       5.589 , 6.0532, 6.09  , 5.8515, 6.1984, 6.603 , 6.3063, 6.292 ,
       6.7497, 6.7473, 6.3705, 2.268 , 2.8217, 2.9044, 3.1746, 3.5742,
       3.3516, 3.3957, 3.2943, 3.7544, 3.5478, 3.8203, 3.325 , 3.8   ,
       3.8352, 3.6312, 4.1272, 3.906 , 4.4968, 4.7736, 5.355 , 4.2476,
       4.2485, 4.6816, 6.562 , 6.5736, 6.525 , 2.3265, 2.3142, 2.673 ,
       2.9181, 3.2928, 3.2944, 3.4104, 3.1571, 3.6636, 4.144 , 4.234 ,
       1.408 , 1.9992, 2.432 , 2.6316, 2.9415, 3.3216, 3.1234, 3.0502,
       3.0368, 2.772 , 3.555 , 3.3075, 3.6675, 3.534 , 3.4075, 3.525 ,
       3.525 , 3.525 , 3.995 , 3.624 , 3.624 , 3.63  , 3.626 , 3.725 ,
       3.723 , 3.825 , 4.1658, 3.6835, 4.239 , 4.144 , 5.1373, 4.335 ,
       4.335 , 4.5662, 4.2042, 4.6354, 4.7716, 6.018 , 6.3875, 7.7957,
      

In [30]:
X_train2,X_test2,Y_train2,Y_test2=train_test_split(X2,Y2,test_size=0.2,random_state=2)

In [31]:
lr2=MyMLR()

In [32]:
lr2.fit(X_train2,Y_train2)

In [33]:
y_pred = lr2.predict(X_test2)

In [34]:
from sklearn.metrics import r2_score

In [35]:
r2_score(Y_test2,y_pred)

0.8632446610237773

In [36]:
lr2.b

0.34689475063287945

In [37]:
lr2.m

array([ 2.05847503e-04,  8.24834223e-02,  5.64151788e-01, -5.45092204e-01,
        3.13690075e-01])

# **MLR (skleran)**

In [38]:
lr.fit(X_train2,Y_train2)

LinearRegression()

In [39]:
y_pred1 = lr.predict(X_test2)

In [40]:
r2_score(Y_test2,y_pred1)

0.8632446610242605

In [41]:
lr.coef_

array([ 2.05847503e-04,  8.24834223e-02,  5.64151788e-01, -5.45092204e-01,
        3.13690075e-01])

In [42]:
lr.intercept_

0.346894750632047